[package]
name = "simple-api-rust"
version = "0.1.0"
authors = ["bushiyama <bushiyama.haru@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"